name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.14', '1.18' ]
        dir: [ './azuredevops', './azuredevops/v6', './azuredevops/v7.1']
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Get dependencies
      working-directory: ${{ matrix.dir }}
      run: go get github.com/google/uuid

    - name: go build
      working-directory: ${{ matrix.dir }}
      run: go build -v ./...

    - name: go fmt
      working-directory: ${{ matrix.dir }}
      run: go fmt ./...

    - name: go vet
      working-directory: ${{ matrix.dir }}
      run: go vet ./...

    - name: go test
      working-directory: ${{ matrix.dir }}
      run: go test ./...
